Curse home2
ConducereIT/APV pull request #34
Opened 2024-04-09 21:29 UTC by RaduMiu

missing the right maps, the right pdf rule and design photos

2024-04-10 15:28 UTC, MDGcode requested changes

2024-04-10 15:28 UTC, MDGcode commented on client/src/components/CurseHome.tsx
> +                <button
Too much padding on buttons, also add more margin between buttons

2024-04-10 15:28 UTC, MDGcode commented on client/src/components/CurseHome.tsx
> +    <div className="w-full px-[var(--bs-gutter-x,.75rem)]   bg-customBackground  ">
The component is out of proportions
https://imgur.com/a/f2X8RpQ

2024-04-10 15:28 UTC, MDGcode commented on client/src/components/CurseHome.tsx
> +        setMapSrc(
Same problem with 
https://imgur.com/5P2NtBV

2024-04-10 15:28 UTC, MDGcode commented on client/src/components/CurseHome.tsx
> +            <div className="md:w-1/4 mb-4 md:mb-0 md:mr-4 overflow-x-auto">
Make it so only 3 buttons are visible at a time on mobile

2024-04-12 18:30 UTC, AMihneaa requested changes
The component seems to be generated with ChatGPT. It's good to use it, but it's preferable not to rely solely on it. The styling of the component is lacking; it lacks the human touch that can perceive and understand.

2024-04-12 18:30 UTC, AMihneaa commented on client/src/components/CurseHome.tsx
> +  const [allForOneText2, setAllForOneText2] = useState("Tocmai în spiritul caritabil din care s-a și născut Aleargă Pentru Viață, participanții sunt încurajați să ofere drept donație pentru Florin câ
Having too many useState calls suggests you should aim for fewer. You can wrap them in a single state and think smarter about your update commands. Your code lacks modularity; hence, the component should have been designed differently from the start

2024-04-12 18:30 UTC, AMihneaa commented on client/src/components/CurseHome.tsx
> +        break;
The component lacks modularity.
I'd like it to be able to receive an external parameter of type JSON with a unique type defined within it.

2024-04-12 18:30 UTC, AMihneaa commented on client/src/components/CurseHome.tsx
> +                        <button
All of these have the same structure, so there should be just one where you map based on what you have in the JSON. It's unnecessary to change the characteristics of the component like that.

2024-04-12 18:30 UTC, AMihneaa commented on client/src/components/CurseHome.tsx
> +                        {/* <h2 className="text-3xl font-bold">{selectedCategory}</h2> */}
Remove redundant comments from the code; they make it harder to read.

2024-04-12 18:30 UTC, AMihneaa commented on client/src/views/Home.view.tsx
> -      />
Remove redundant comments from the code; they make it harder to read.

2024-04-12 18:30 UTC, AMihneaa commented on client/tailwind.config.js
> +
"Go for a darker shade.

2024-04-12 18:30 UTC, AMihneaa commented on client/tailwind.config.js
> +
Don't use 'px', but 'rem' instead.

2024-04-12 18:30 UTC, AMihneaa commented on client/src/components/CurseHome.tsx
> +import flyingImg4 from "../assets/flyingImg4.png";
Find shorter, more accurate and intuitive names

2024-04-13 17:11 UTC, closed without merging